### ISSUE TITLE
Can we extract the bit masks used for entity metadata parsing

### ISSUE THREAD

**Issue by u9g** [Pokechu22/Burger#17]
Like here: https://wiki.vg/Entity_metadata#Entity to extract this table 

bit mask | description
-- | --
0x01 | Is on fire
0x02 | Is crouching
0x04 | Unused (previously riding)
0x08 | Is sprinting
0x10 | Is swimming
0x20 | Is invisible
0x40 | has glowing effect
0x80 | Is flying with an elytra

and here: https://wiki.vg/Entity_metadata#Living_Entity

bit mask | description
-- | --
0x01 | Is hand active
0x02 | Active hand (0 = main hand, 1 = offhand)
0x04 | Is in riptide spin attack

and so on

**Comment by Pokechu22** [comment]
No, I don't think that's feasible to extract.  Burger currently looks for the declaration of the entity metadata field, and then for its initialization.  Figuring out if something is a bitfield, and what the different parts of it are, is much more complicated (especially since some bitfields such as the Entity one don't have all of the bits managed directly in Entity, but instead by subclasses).
